-- Enable RLS on security-sensitive tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE reporting_years ENABLE ROW LEVEL SECURITY;
ALTER TABLE sectors ENABLE ROW LEVEL SECURITY;
ALTER TABLE sector_provinces ENABLE ROW LEVEL SECURITY;
ALTER TABLE beneficiary_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE branding_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_provinces ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_districts ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_communities ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_beneficiaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_clusters ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_standard_sectors ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_phases ENABLE ROW LEVEL SECURITY;
ALTER TABLE baseline_surveys ENABLE ROW LEVEL SECURITY;
ALTER TABLE baseline_enumerator_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE data_collection_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE baseline_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE enumerators ENABLE ROW LEVEL SECURITY;
ALTER TABLE field_visit_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE stories ENABLE ROW LEVEL SECURITY;
ALTER TABLE findings ENABLE ROW LEVEL SECURITY;
ALTER TABLE distribution_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE pdm_surveys ENABLE ROW LEVEL SECURITY;
ALTER TABLE pdm_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_access_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE integrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE complaint_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE complaint_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_awareness_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE cluster_catalog ENABLE ROW LEVEL SECURITY;
ALTER TABLE sector_catalog ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_sessions ENABLE ROW LEVEL SECURITY;

-- Default deny for anonymous access
CREATE POLICY anon_block_users ON users FOR ALL TO anon USING (false);
CREATE POLICY anon_block_reporting_years ON reporting_years FOR ALL TO anon USING (false);
CREATE POLICY anon_block_sectors ON sectors FOR ALL TO anon USING (false);
CREATE POLICY anon_block_sector_provinces ON sector_provinces FOR ALL TO anon USING (false);
CREATE POLICY anon_block_beneficiary_stats ON beneficiary_stats FOR ALL TO anon USING (false);
CREATE POLICY anon_block_branding_settings ON branding_settings FOR ALL TO anon USING (false);
CREATE POLICY anon_block_projects ON projects FOR ALL TO anon USING (false);
CREATE POLICY anon_block_project_provinces ON project_provinces FOR ALL TO anon USING (false);
CREATE POLICY anon_block_project_districts ON project_districts FOR ALL TO anon USING (false);
CREATE POLICY anon_block_project_communities ON project_communities FOR ALL TO anon USING (false);
CREATE POLICY anon_block_project_beneficiaries ON project_beneficiaries FOR ALL TO anon USING (false);
CREATE POLICY anon_block_project_clusters ON project_clusters FOR ALL TO anon USING (false);
CREATE POLICY anon_block_project_standard_sectors ON project_standard_sectors FOR ALL TO anon USING (false);
CREATE POLICY anon_block_project_documents ON project_documents FOR ALL TO anon USING (false);
CREATE POLICY anon_block_project_phases ON project_phases FOR ALL TO anon USING (false);
CREATE POLICY anon_block_baseline_surveys ON baseline_surveys FOR ALL TO anon USING (false);
CREATE POLICY anon_block_baseline_enumerator_assignments ON baseline_enumerator_assignments FOR ALL TO anon USING (false);
CREATE POLICY anon_block_data_collection_tasks ON data_collection_tasks FOR ALL TO anon USING (false);
CREATE POLICY anon_block_baseline_reports ON baseline_reports FOR ALL TO anon USING (false);
CREATE POLICY anon_block_enumerators ON enumerators FOR ALL TO anon USING (false);
CREATE POLICY anon_block_field_visit_reports ON field_visit_reports FOR ALL TO anon USING (false);
CREATE POLICY anon_block_monthly_reports ON monthly_reports FOR ALL TO anon USING (false);
CREATE POLICY anon_block_evaluations ON evaluations FOR ALL TO anon USING (false);
CREATE POLICY anon_block_stories ON stories FOR ALL TO anon USING (false);
CREATE POLICY anon_block_findings ON findings FOR ALL TO anon USING (false);
CREATE POLICY anon_block_distribution_records ON distribution_records FOR ALL TO anon USING (false);
CREATE POLICY anon_block_pdm_surveys ON pdm_surveys FOR ALL TO anon USING (false);
CREATE POLICY anon_block_pdm_reports ON pdm_reports FOR ALL TO anon USING (false);
CREATE POLICY anon_block_lessons ON lessons FOR ALL TO anon USING (false);
CREATE POLICY anon_block_knowledge_resources ON knowledge_resources FOR ALL TO anon USING (false);
CREATE POLICY anon_block_user_access_assignments ON user_access_assignments FOR ALL TO anon USING (false);
CREATE POLICY anon_block_integrations ON integrations FOR ALL TO anon USING (false);
CREATE POLICY anon_block_complaints ON complaints FOR ALL TO anon USING (false);
CREATE POLICY anon_block_complaint_metadata ON complaint_metadata FOR ALL TO anon USING (false);
CREATE POLICY anon_block_complaint_responses ON complaint_responses FOR ALL TO anon USING (false);
CREATE POLICY anon_block_crm_awareness_records ON crm_awareness_records FOR ALL TO anon USING (false);
CREATE POLICY anon_block_cluster_catalog ON cluster_catalog FOR ALL TO anon USING (false);
CREATE POLICY anon_block_sector_catalog ON sector_catalog FOR ALL TO anon USING (false);
CREATE POLICY anon_block_user_sessions ON user_sessions FOR ALL TO anon USING (false);
